version: '3.5'
services:
  sql-parser_postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
#    restart: unless-stopped
    ports:
      - '6543:5432'
    env_file:
      - .env
    networks:
      - sql-parser_net

  sql-parser_app:
    container_name: sql-parser_app
    depends_on:
      [sql-parser_postgres]
#    restart: unless-stopped
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .app-env
      - .env
    volumes:
            - ./scripts:/${SQL_SCRIPTS_PATH}
    networks:
      - sql-parser_net

networks:
  sql-parser_net:
    name: sql-parser_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.11.0/24
